# This workflow will run the project tests on a push to a non-master branch or when a pull request to master is created.
# It will also run the tests on the master branch at mid-day everyday.

name: Run Tests

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      -'v*'
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 12 * * *'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Run Tests
      run: mvn verify

